In [1]:
import numpy as np 
from sklearn.model_selection import train_test_split 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 


X = np.array([
    [0.5, 1.0],  
    [1.0, 1.5],  
    [4.0, 3.0],  
    [5.0, 4.0],  
    [0.2, 0.5]    
]) 

# Labels: 0 = Unhealthy, 1 = Healthy
y = np.array([[0], [0], [1], [1], [0]]) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42) 


model = Sequential() 

model.add(Dense(4, input_dim=2, activation='relu')) 


model.add(Dense(1, activation='sigmoid')) 

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 

print("Starting training...")
model.fit(X_train, y_train, epochs=200, verbose=0) 
print("Training complete.")

predictions = model.predict(X_test) 
predicted_classes = (predictions >= 0.5).astype(int) 


print("\n--- Results ---")
print("Test Inputs (Exercise, Water):") 
print(X_test) 

print("\nPredicted Probabilities (Raw Output):") 
print(predictions) 

print("\nPredicted Class Labels (1=Healthy, 0=Unhealthy):") 
print(predicted_classes)

print("\nActual Labels:")
print(y_test)

c:\Users\SS\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Starting training...
Training complete.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

--- Results ---
Test Inputs (Exercise, Water):
[[1.  1.5]]

Predicted Probabilities (Raw Output):
[[0.54321605]]

Predicted Class Labels (1=Healthy, 0=Unhealthy):
[[1]]

Actual Labels:
[[0]]


In [2]:
import numpy as np 
from sklearn.model_selection import train_test_split 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

X = np.array([
    [1, 40],   
    [2, 50],  
    [8, 85],  
    [9, 95],   
    [5, 70]    
]) 

# Labels: 1 = Pass, 0 = Fail
y = np.array([[0], [0], [1], [1], [1]]) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42) 
model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu')) 
model.add(Dense(1, activation='sigmoid')) 
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 

model.fit(X_train, y_train, epochs=100, verbose=0) 

predictions = model.predict(X_test) 

predicted_classes = (predictions >= 0.5).astype(int) 

print("Test Inputs (Assignments, Attendance):") 
print(X_test)

print("\nPredicted Class Labels (1=Pass, 0=Fail):") 
print(predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
Test Inputs (Assignments, Attendance):
[[ 2 50]
 [ 5 70]]

Predicted Class Labels (1=Pass, 0=Fail):
[[1]
 [1]]


In [3]:
import numpy as np 
from sklearn.model_selection import train_test_split 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

X = np.array([
    [2000, 580], 
    [3500, 620], 
    [8000, 750], 
    [5500, 710], 
    [9000, 800]
]) 

# Target: 1 = Eligible, 0 = Not Eligible
y = np.array([[0], [0], [1], [1], [1]]) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42) 

model = Sequential() 

model.add(Dense(4, input_dim=2, activation='relu')) 

model.add(Dense(1, activation='sigmoid')) 

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 

model.fit(X_train, y_train, epochs=150, verbose=0) 

predictions = model.predict(X_test) 

predicted_classes = (predictions >= 0.5).astype(int) 

print("Test Inputs (Income, Credit Score):") 
print(X_test)

print("\nPredicted Probabilities:") 
print(predictions) 

print("\nPredicted Class Labels (1=Eligible, 0=Not Eligible):") 
print(predicted_classes)

c:\Users\SS\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Test Inputs (Income, Credit Score):
[[3500  620]
 [9000  800]]

Predicted Probabilities:
[[0.]
 [0.]]

Predicted Class Labels (1=Eligible, 0=Not Eligible):
[[0]
 [0]]
