In [1]:
import numpy as np

arr = np.array([[0, 1], [2, 3]])
print("Original array:\n", arr)

flat_arr = arr.flatten()

print("Maximum value of the above flattened array:", flat_arr.max())
print("Minimum value of the above flattened array:", flat_arr.min())


Original array:
 [[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [4]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values from 2 to 10:\n", matrix)


3x3 matrix with values from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])
float_arr = arr.astype(float)

print("Original array:", arr)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [6]:
import numpy as np

M1 = np.array([[5, 5], [0, 1]])
M2 = np.array([[1, 1], [2, 1]])

# Matrix multiplication
result = np.dot(M1, M2)

# Transpose of the result
transpose_result = result.T

print("Matrix M1:\n", M1)
print("Matrix M2:\n", M2)
print("Result of multiplication:\n", result)
print("Transpose of resultant matrix:\n", transpose_result)


Matrix M1:
 [[5 5]
 [0 1]]
Matrix M2:
 [[1 1]
 [2 1]]
Result of multiplication:
 [[15 10]
 [ 2  1]]
Transpose of resultant matrix:
 [[15  2]
 [10  1]]


In [7]:
import numpy as np

A = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
])

# Compute inverse
A_inv = np.linalg.inv(A)

print("Original Matrix A:\n", A)
print("Inverse of Matrix A:\n", A_inv)


Original Matrix A:
 [[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
Inverse of Matrix A:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
